display:
  color_displays:
    - title: "cross-section"
      fn_name: "cross_section"
      background_color: [135, 206, 235]
      screen_height: 128
      section_idx: 4
      section_dim: "x"
      levels:
        - key: "${key:terrain,elevation}"
          color: [130, 110, 127]
          scale: 100.0
        - key: "${key:terrain,soil_volume}"
          color: [180, 160, 127]
          color_mod_key: "${key:terrain,soil_water_saturation}"
#          color_mod: [150, 130, 127]
          color_mod: [0, 0, 255]
          scale: 1.0
        - key: "${key:terrain,surface_water_volume}"
          color: [100, 140, 200]
          scale: 1.0
    - title: "layers"
      fn_name: "layered"
      layers:
        - key: "${key:terrain,elevation}"
          threshold: 0
          color_min: [0, 0, 0]
          color_max: [127, 127, 127]
          input_range: [0, 1]
        - key: "${key:terrain,surface_water_volume}"
          threshold: 0.5
          color_min: [0, 0, 128]
          color_max: [0, 0, 255]
          input_range: [0, 20]
        - key: "${key:plant,energy}"
          threshold: 1
          color_min: [0, 32, 16]
          color_max: [0, 255, 127]
          input_range: [0, 255]
    - title: "soil_sat_coefficient"
      fn_name: "layered"
      layers:
        - key: "${key:plant,soil_sat_coeff}"
          threshold: -3
          color_min: [255, 0, 0]
          color_max: [0, 255, 0]
          input_range: [-2.5, 2.5]
    - title: "soil_water_saturation"
      fn_name: "layered"
      layers:
        - key: "${key:terrain,soil_water_saturation}"
          threshold: 0
          color_min: [0, 0, 0]
          color_max: [255, 255, 255]
          input_range: [0, 1]
    - title: "available_sat"
      fn_name: "layered"
      layers:
        - key: "${key:terrain,surface_water_volume}"
          threshold: 0.0
          color_min: [0, 0, 0]
          color_max: [255, 255, 255]
          input_range: [0, 0.5]

world:
  device: auto
  running: True
  max_ups: 0
  size: [256, 256]  # [Height, Width]

  entities:
    Terrain:
      elevation:
        perlin:
          scale: [4, 4]
        ramp:
      surface_water_volume:
        rainfall_rate: 5.7e-6
        flow_rate: 0.15
        relaxation_factor: 1.0
        steps: 1
      soil_water_volume:
        field_capacity: 0.55
        infiltration_rate: 2e-7
        flow_rate: 0.1
        saturation_gradient_coeff: 0.3
      soil_volume:
        erosion_rate: 0.05
        init_scale: 10.0

    Plant:
      initial_energy: 32
      init_prob: 0.02
      growth_prob: 10.0
      germination_prob: 0.005
      seed_prob: 0.05

    Herbivore:
      initial_energy: 240
      init_odds: 255
      eat_max: 16
      energy_loss: 2
      divide_threshold: 250
      toy_init: False
      target_key: plant
      target_weights: [0.5]
      opposite_key: [herbivore, predator]
      opposite_weights: [0.1, 5.0]
      food_key: plant
