[project]
name = "tensor_beasts"
version = "0.0.1"
description = "Ecological simulation that mostly uses tensor operations."
readme = "README.md"
authors = [{name = "kevin", email = "kjhenner@gmail.com"}]
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.5.2",
    "PyOpenGL>=3.1.7",
    "torch>=2.4.0",
    "pytest>=8.2.1",
    "numpy>=1.26.4",
    "pydantic>=2.7.3",
    "imageio>=2.34",
    "imageio-ffmpeg>=0.5",
    "wandb>=0.17.3",
    "rich>=13.7.1",
    "matplotlib>=3.9.2",
    "omegaconf>=2.3.0",
    "tensordict>=0.4.0",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["tensor_beasts*"]
