display:
  color_displays:
    - title: "elevation"
      entity: Terrain
      feature: elevation
    - title: "surface_water_volume"
      entity: Terrain
      feature: surface_water_volume
    - title: "soil_water_volume"
      entity: Terrain
      feature: soil_water_volume
  text_displays:
    - title: "elevation"
      entity: Terrain
      feature: elevation
    - title: "surface_water_volume"
      entity: Terrain
      feature: surface_water_volume
    - title: "soil_water_volume"
      entity: Terrain
      feature: soil_water_volume

world:
  device: auto
  running: True
  max_ups: 0
  size: [64, 64]  # [Height, Width]

  entities:
    Terrain:
      elevation:
        perlin:
          scale: [4, 4]
        ramp:
      surface_water_volume:
        rainfall_rate: 5.7e-5
      soil_water_volume:
        infoltration_rate: 1e-5
        flow_rate: 1e-5
#
#    plant:
#      initial_energy: 32
#      init_prob: 0.02
#      growth_prob: 0.5
#      germination_prob: 0.005
#      seed_prob: 0.05
#      water_key: [terrain, water_level]
