display:
  screens:
#    - entity_name: plant
#      feature_name: energy
    - entity_name: terrain
      feature_name: elevation
    - entity_name: terrain
      feature_name: water_level
#    - entity_name: terrain
#      feature_name: inflow
#    - entity_name: terrain
#      feature_name: outflow

world:
  device: auto
  running: True
  max_ups: 0
  size: [256, 256]  # [Height, Width]

  entities:
    terrain:
#      rainfall_rate: 5.7e-06
      rainfall_rate: 5.7e-05
      flow_rate: 0.0105
      evaporation_rate: 0.001
      elevation_max: 500
      surface_water_max: 10
      soil_max: 10
      soil_porosity: 0.4
      elevation:
        perlin:
          scale: [4, 4]
        ramp:
#
#    plant:
#      initial_energy: 32
#      init_prob: 0.02
#      growth_prob: 0.5
#      germination_prob: 0.005
#      seed_prob: 0.05
#      water_key: [terrain, water_level]
