# Basic simulation config
# Inherits shared behavioral settings from base, sets size and display

_base: "conf/base/simulation.yaml"

display:
  color_displays:
    - title: "predator_scent"
      fn_name: "default"
      key: "${key:predator,scent}"
      input_range: [0, 255]

    - title: "herbivore_scent"
      fn_name: "default"
      key: "${key:herbivore,scent}"
      input_range: [0, 255]

    - title: "plant_scent"
      fn_name: "default"
      key: "${key:simpleplant,scent}"
      input_range: [0, 255]

    - title: "carrion_scent"
      fn_name: "default"
      key: "${key:simpleterrain,carrion_scent}"
      input_range: [0, 255]

    - title: "layers"
      fn_name: "layered"
      layers:
        - key: "${key:simpleplant,energy}"
          threshold: 1
          color_min: [0, 32, 16]
          color_max: [0, 255, 127]
          input_range: [0, 255]
        - key: "${key:herbivore,biomass}"
          threshold: 1
          color_min: [0, 0, 64]
          color_max: [0, 0, 255]
          input_range: [0, 255]
        - key: "${key:predator,biomass}"
          threshold: 1
          color_min: [64, 0, 0]
          color_max: [255, 0, 0]
          input_range: [0, 255]

    - title: "biomass"
      fn_name: "layered"
      layers:
        - key: "${key:herbivore,biomass}"
          threshold: 1
          color_min: [0, 0, 64]
          color_max: [0, 0, 255]
          input_range: [0, 255]
        - key: "${key:predator,biomass}"
          threshold: 1
          color_min: [64, 0, 0]
          color_max: [255, 0, 0]
          input_range: [0, 255]

    - title: "water_level"
      fn_name: "default"
      key: "${key:simpleterrain,simple_water}"
      input_range: [0, 1]

    - title: "growth_coeff"
      fn_name: "layered"
      layers:
        - key: "${key:simpleplant,growth_coeff}"
          threshold: -3
          color_min: [255, 0, 0]
          color_max: [0, 255, 0]
          input_range: [-2.5, 2.5]

world:
  size: [512, 512]
